#sdocument: https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    site_name: My Easy Admin
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'F j, Y H:i'
    list:
        max_results: 20
    design:
        form_theme: 'vertical'
        # this backend uses turquoise as its main color
        brand_color: 'rgba(26, 188, 156, 0.85)'
    entities:
        User:
            # disabled_actions: ['delete', 'edit', 'restock']
            label: 'User Web Master'
            class: Dao\DataSourceBundle\Entity\User
            search:
                fields: ['id', 'username', 'email', 'lastLogin', 'enabled', 'locked']
            list:
                title: "User list"
                fields:
                    - id
                    - username
                    - email
                    - lastLogin
                    - { property: 'enabled', type: 'boolean' }
                    - { property: 'locked', type: 'boolean' }
                actions: ['-show']
            form:
                fields:
                    - { property: 'username' }
                    - { property: 'email', type: 'email' }
                    - { property: 'plainPassword', type: 'password', label: 'Password', help: 'Passwords must have at least 8 characters' }
                    - { property: 'enabled', type: 'checkbox' }
                    - { property: 'locked', type: 'checkbox' }

        #customer entity
#        Customer:
#            class: Dao\DataSourceBundle\Entity\Customer
#            list:
#                fields:
#                    - user
#                    - name
#                    - { property: 'logo', type: 'image', base_path: 'http://localhost/dev/thelastsf2/web/images/customers/' }
#                    - email
#                    - createdAt
#                actions:
#                    - { name: 'show', icon: 'search', label: false }
#                    - { name: 'edit', icon: 'pencil', label: false }
#            show:
#                fields:
#                    - user
#                    - name
#                    - { property: 'logo', type: 'image', base_path: 'http://localhost/dev/thelastsf2/web/images/customers/' }
#                    - firstName
#                    - lastName
#                    - email
#                    - phone
#                    - companyName
#                    - website
#            form:
#                fields:
#                    - user
#                    - name
#                    - { property: 'logoFile', type: 'file', label: 'Upload logo', help: 'Select file to upload / change logo' }
#                    - firstName
#                    - lastname
#                    - { property: 'email', type: 'email' }
#                    - phone
#                    - companyName
#                    - website
        #post entity
        # https://github.com/javiereguiluz/EasyAdminBundle/blob/master/Resources/doc/getting-started/4-views-and-actions.md
        # https://github.com/javiereguiluz/EasyAdminBundle/blob/master/Resources/doc/tutorials/customizing-backend-actions.md
        Post:
            label: 'Article Store'
            class: Dao\DataSourceBundle\Entity\Post
            search:
                fields: ['id', 'title', 'slug', 'tags', 'authorEmail', 'publishedAt', 'updatedAt', 'createdAt']
            # image_base_path: 'http://static.acme.org/img/'
            image_base_path: 'http://localhost/my/thelastsf2/web/uploads/posts/'
            list:
                title: 'Article List'
                fields:
                    - id
                    - title
                    - { property: 'photo', type: 'image' }
                    - slug
                    #- summary
                    - tags
                    - { property: 'publishedAt', format: 'F j, Y' }
                    - authorEmail
                    - updatedAt
                    - createdAt
                actions:
                    - { name: 'show', icon: 'search', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'restock', type: 'method' }
            show:
                fields:
                    - id
                    - title
                    - { property: 'photo', type: 'image' }
                    - slug
                    - { property: 'summary', type: 'textarea' }
                    - { property: 'content', type: 'textarea' }
                    - tags
                    - publishedAt
                    - authorEmail
                    - updatedAt
                    - createdAt
            form:
                fields:
                    - title
                    - { property: 'summary', type: 'textarea' }
                    - { property: 'content', type: 'textarea' }
                    - tags
                    - { property: 'photoFile', type: 'file', label: 'Upload photo', help: 'Select file to upload / change photo' }
                    - authorEmail
                    - publishedAt
        #Comment entity
        Comment:
            label: 'User Comment'
            class: Dao\DataSourceBundle\Entity\Comment
            list:
                title: 'Comment List'
                fields:
                    - id
                    - post
                    #- { property: 'logo', type: 'image', base_path: 'http://localhost/sf2-easyadmin/web/images/customers/' }
                    - comment
                    - authorEmail
                    - { property: 'publishedAt', format: 'F j, Y' }
                    - updatedAt
                    - createdAt
                actions:
                    - { name: 'show', icon: 'search', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
            show:
                fields:
                    - id
                    - post
                    #- { property: 'logo', type: 'image', base_path: 'http://localhost/sf2-easyadmin/web/images/customers/' }
                    - comment
                    - authorEmail
                    - publishedAt
                    - updatedAt
                    - createdAt
            form:
                form_options: { validation_groups: ['Default', 'my_validation_group'] }
                fields:
                    - post
                    - { property: 'comment', type: 'textarea', label: 'Comment', class: 'none_tinymce' }
                    #- { property: 'logoFile', type: 'file', label: 'Upload logo', help: 'Select file to upload / change logo' }
                    - authorEmail
                    - publishedAt